### ISSUE TITLE
"No admin user." not useful (security by obscurity)

### ISSUE THREAD

**Issue by Zodiac1978** [aurooba/wpaudit.site#11]
The REST API is showing every user (if not closed):
https://developer.wordpress.org/rest-api/reference/users/

Also this is not classified as insecure by core:

> It has been stated in previous tickets, "leaking" of the username is not deemed a security issue by WordPress.org, as it's a conscious decision to use the username as the slug in the URL, If you don't like this default behaviour, there are plugins in the repository which allow you to change the url format to your preferred layout.
https://core.trac.wordpress.org/ticket/20235#comment:7

I would recommend to rephrase or remove this.

**Comment by aurooba** [comment]
Hey @Zodiac1978! Thanks for your suggestion. The point you bring about the REST API is very true, and I'm going to add a point in the checklist about hiding the users list. :) The reason I recommend not having an admin user is because I've seen a LOT of websites get DDos-ed by bots who crash the system by attempting to log in with the `admin` user and attempting to 'reset' the password, etc. It's quite a common problem. By not having an `admin` user and combining it with limiting login attempts, it helps mitigate a practical problem. :)

**Comment by Zodiac1978** [comment]
> attempting to 'reset' the password

Okay that is bad. Never saw this happening, but if this happens it will be very annoying.

**Comment by aurooba** [comment]
It really is quite annoying. So although it doesn't pose a REAL security threat, it addresses a practical problem a lot of website owners (at least in North America) face.
