### ISSUE TITLE
Rename GTMetrix to Speedtest and add more links

### ISSUE THREAD

**Issue by Zodiac1978** [aurooba/wpaudit.site#14]
Instead of "Run GTmetrix" you could name it "Speedtest(ing)" and add more links:
https://tools.pingdom.com/
and
https://www.webpagetest.org/

**Comment by aurooba** [comment]
Thanks for the suggestion! 

I hadn't included other resources because GTMetrics is comparatively more comprehensive, and WPAudit is a fairly opinionated resource written in my personal voice. Combining that with the `Run a Lighthouse check` catches pretty much everything.

However, it's on my list to update and add pingdom, since I use it a lot myself to check against servers in different regions. :)
